<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="leagueOfLegends" nsURI="https://tdt4250/project/leagueOfLegends"
    nsPrefix="tdt4250.project.leagueOfLegends">
  <eClassifiers xsi:type="ecore:EClass" name="League">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" upperBound="-1"
        eType="#//Team" containment="true" eOpposite="#//Team/league"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seasons" upperBound="-1"
        eType="#//Season" containment="true" eOpposite="#//Season/league"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="champions" upperBound="-1"
        eType="#//Champion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Champion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="championStat" eType="#//ChampionsStats"
        containment="true" eOpposite="#//ChampionsStats/champion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="league" lowerBound="1"
        eType="#//League" eOpposite="#//League/teams"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="5"
        upperBound="-1" eType="#//Player" containment="true" eOpposite="#//Player/team"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="winLossRatio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="championPool" upperBound="-1"
        eType="#//Champion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playerStats" lowerBound="1"
        eType="#//PlayerStats" containment="true" eOpposite="#//PlayerStats/player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="team" lowerBound="1" eType="#//Team"
        eOpposite="#//Team/player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlayerStats">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gamesPlayed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="careerKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="careerDeaths" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="careerAssist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="killDeathAssistRatio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="winLoseRatio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Player" eOpposite="#//Player/playerStats"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wins" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match">
    <eStructuralFeatures xsi:type="ecore:EReference" name="games" upperBound="-1"
        eType="#//Game" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DisplayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bestOF" eType="#//BestOf"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" lowerBound="2" upperBound="2"
        eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="week" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gameID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameStats" lowerBound="1"
        eType="#//GameStats" containment="true" eOpposite="#//GameStats/game"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redTeam" lowerBound="1"
        eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blueTeam" lowerBound="1"
        eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameTeamStat" lowerBound="2"
        upperBound="2" eType="#//GameTeamStats" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gamePlayerStats" upperBound="-1"
        eType="#//GamePlayerStats" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="winner" eType="#//Side"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameTeamStats">
    <eStructuralFeatures xsi:type="ecore:EReference" name="team" lowerBound="1" eType="#//Team"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalDeaths" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAssist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalGolds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalWards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalWardsKilled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalVisionWards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalMinionKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalMonsterKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teamBaronKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teamSide" eType="#//Side"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamePlayerStats">
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Player"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deaths" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="golds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wardsKilled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visionWards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minionKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monsterKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="champion" eType="#//Champion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BestOf">
    <eLiterals name="QF" value="5" literal="QF"/>
    <eLiterals name="F" value="5"/>
    <eLiterals name="SF" value="5" literal="SF"/>
    <eLiterals name="Regular" value="1" literal="Regular"/>
    <eLiterals name="R1" value="5"/>
    <eLiterals name="R2" value="5"/>
    <eLiterals name="R3" value="5"/>
    <eLiterals name="_3p" value="5" literal="_3p"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Position">
    <eLiterals name="middle"/>
    <eLiterals name="top" value="1"/>
    <eLiterals name="jungle" value="2"/>
    <eLiterals name="adc" value="3"/>
    <eLiterals name="support" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Side">
    <eLiterals name="red"/>
    <eLiterals name="blue" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Season">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SplitName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="matches" upperBound="-1"
        eType="#//Match" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="league" lowerBound="1"
        eType="#//League" eOpposite="#//League/seasons"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="splitType" eType="#//SplitType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameStats">
    <eStructuralFeatures xsi:type="ecore:EReference" name="game" lowerBound="1" eType="#//Game"
        eOpposite="#//Game/gameStats"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="winner" eType="#//Side"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalDeaths" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAssist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalGolds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalWards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalWardsKilled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalVisionWards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalMinionKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalMonsterKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="teamBaronKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SplitType">
    <eLiterals name="regular" literal="regular"/>
    <eLiterals name="playoff" value="1"/>
    <eLiterals name="regionals" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChampionsStats">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gamesPlayed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalKills" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalDeaths" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAssist" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="killDeathAssistRatio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="champion" eType="#//Champion"
        eOpposite="#//Champion/championStat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bans" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wins" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="winLoseRatio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
</ecore:EPackage>
